services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:4339@db:5432/saberhub
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - db
    command: sh -c "until nc -z db 5432; do echo 'Esperando db...'; sleep 1; done; npx prisma db push && npm start"
    restart: always

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4339
      - POSTGRES_DB=saberhub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: