// @ts-nocheck
import { default as __fd_glob_48 } from "../content/docs/10-legal/meta.json?collection=docs"
import { default as __fd_glob_47 } from "../content/docs/09-development/meta.json?collection=docs"
import { default as __fd_glob_46 } from "../content/docs/08-deployment/meta.json?collection=docs"
import { default as __fd_glob_45 } from "../content/docs/07-security/meta.json?collection=docs"
import { default as __fd_glob_44 } from "../content/docs/06-scraping/meta.json?collection=docs"
import { default as __fd_glob_43 } from "../content/docs/05-frontend/meta.json?collection=docs"
import { default as __fd_glob_42 } from "../content/docs/04-api/meta.json?collection=docs"
import { default as __fd_glob_41 } from "../content/docs/03-database/meta.json?collection=docs"
import { default as __fd_glob_40 } from "../content/docs/01-product/meta.json?collection=docs"
import { default as __fd_glob_39 } from "../content/docs/02-architecture/meta.json?collection=docs"
import { default as __fd_glob_38 } from "../content/docs/00-overview/meta.json?collection=docs"
import { default as __fd_glob_37 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_36 from "../content/docs/10-legal/terminos.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/10-legal/scraping.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/10-legal/privacidad.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/10-legal/index.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/08-deployment/vercel.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/08-deployment/index.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/08-deployment/env-vars.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/09-development/testing.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/09-development/setup.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/09-development/index.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/07-security/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/07-security/headers.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/07-security/autenticacion.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/07-security/auditoria.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/06-scraping/sources.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/06-scraping/index.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/06-scraping/compliance.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/05-frontend/pages.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/05-frontend/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/05-frontend/components.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/04-api/webhooks.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/04-api/reportes.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/04-api/index.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/04-api/evaluaciones.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/04-api/cursos.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/04-api/certificados.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/04-api/autenticacion.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/03-database/schema.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/03-database/models.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/03-database/index.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/00-overview/index.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/01-product/roles.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/01-product/index.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/01-product/features.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/02-architecture/stack.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/02-architecture/index.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/02-architecture/data-flow.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_37, "00-overview/meta.json": __fd_glob_38, "02-architecture/meta.json": __fd_glob_39, "01-product/meta.json": __fd_glob_40, "03-database/meta.json": __fd_glob_41, "04-api/meta.json": __fd_glob_42, "05-frontend/meta.json": __fd_glob_43, "06-scraping/meta.json": __fd_glob_44, "07-security/meta.json": __fd_glob_45, "08-deployment/meta.json": __fd_glob_46, "09-development/meta.json": __fd_glob_47, "10-legal/meta.json": __fd_glob_48, }, {"02-architecture/data-flow.mdx": __fd_glob_0, "02-architecture/index.mdx": __fd_glob_1, "02-architecture/stack.mdx": __fd_glob_2, "01-product/features.mdx": __fd_glob_3, "01-product/index.mdx": __fd_glob_4, "01-product/roles.mdx": __fd_glob_5, "00-overview/index.mdx": __fd_glob_6, "03-database/index.mdx": __fd_glob_7, "03-database/models.mdx": __fd_glob_8, "03-database/schema.mdx": __fd_glob_9, "04-api/autenticacion.mdx": __fd_glob_10, "04-api/certificados.mdx": __fd_glob_11, "04-api/cursos.mdx": __fd_glob_12, "04-api/evaluaciones.mdx": __fd_glob_13, "04-api/index.mdx": __fd_glob_14, "04-api/reportes.mdx": __fd_glob_15, "04-api/webhooks.mdx": __fd_glob_16, "05-frontend/components.mdx": __fd_glob_17, "05-frontend/index.mdx": __fd_glob_18, "05-frontend/pages.mdx": __fd_glob_19, "06-scraping/compliance.mdx": __fd_glob_20, "06-scraping/index.mdx": __fd_glob_21, "06-scraping/sources.mdx": __fd_glob_22, "07-security/auditoria.mdx": __fd_glob_23, "07-security/autenticacion.mdx": __fd_glob_24, "07-security/headers.mdx": __fd_glob_25, "07-security/index.mdx": __fd_glob_26, "09-development/index.mdx": __fd_glob_27, "09-development/setup.mdx": __fd_glob_28, "09-development/testing.mdx": __fd_glob_29, "08-deployment/env-vars.mdx": __fd_glob_30, "08-deployment/index.mdx": __fd_glob_31, "08-deployment/vercel.mdx": __fd_glob_32, "10-legal/index.mdx": __fd_glob_33, "10-legal/privacidad.mdx": __fd_glob_34, "10-legal/scraping.mdx": __fd_glob_35, "10-legal/terminos.mdx": __fd_glob_36, });